[mypy]
strict = False

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-networkx.*]
ignore_missing_imports = True

[mypy-streamlit_agraph.*]
ignore_missing_imports = True

[mypy-stqdm.*]
ignore_missing_imports = True

[mypy-tqdm.*]
ignore_missing_imports = True
